import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
import { getProductsPaginated } from '@/data'
import ProductCard from '@/components/ProductCard'
import Paginator from '@/components/Paginator'

const inter = Inter({ subsets: ['latin'] })
const ipp = 10

export default function Page({products, totalPages, page}) {
  return (
    <>
      <Head>
        <title>Fantasticfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Fantasticfy</h1>
        <div className={styles.container}>
          {products.map(product => <ProductCard product={product} key={product.id}/>)}
        </div>
        <Paginator currentPage={page} totalPages={totalPages}/>
      </main>
    </>
  )
}

export async function getStaticProps({params}) {
  const { page } = params;
  const res = await getProductsPaginated(page, ipp);

  return {
    props: {...res},
  };
}

export async function getStaticPaths() {
  const {totalPages} = await getProductsPaginated(1, ipp);
  const paths = [];

  for (let i = 1; i <= totalPages; i++) {
    paths.push({params: { page: i.toString() }})
  }

  return { paths, fallback: false };
}
