import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { getProductsPaginated } from '@/pages/data'

const inter = Inter({ subsets: ['latin'] })
const ipp = 10

export default function Home({products, totalPages}) {
  return (
    <>
      <Head>
        <title>Fantasticfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {products.map(product => <Link href={`/products/${product.id}`} key={product.id}>{product.title}</Link>)}
        <Link href="/products/page/2">Next</Link>
      </main>
    </>
  )
}

export async function getStaticProps({params}) {
  const { page } = params;
  const res = await getProductsPaginated(page, ipp);

  return {
    props: {...res},
  };
}

export async function getStaticPaths() {
  const {totalPages} = await getProductsPaginated(1, ipp);
  const paths = [];

  for (let i = 1; i <= totalPages; i++) {
    paths.push({params: { page: i.toString() }})
  }

  return { paths, fallback: false };
}
