import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { getAllProducts, getProductById } from '../data'

const inter = Inter({ subsets: ['latin'] })

export default function Home({title}) {
  console.log(title);
  return (
    <>
      <Head>
        <title>Fantasticfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{title}</h1>
        <Link href="/?page=2">Blog Post</Link>
      </main>
    </>
  )
}

export async function getStaticProps({params}) {
  const { id } = params;
  const res = await getProductById(id);

  return {
    props: {...res},
  };
}

export async function getStaticPaths() {
  const res = await getAllProducts();

  const paths = res.products.map((p) => ({
    params: { id: p.id.toString() },
  }));
 
  return { paths, fallback: false };
}